name: github pages

on:
  push:
    branches:
      - 'releases/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      -
        name: Purge npm/nodejs
        run: |
          sudo apt-get remove -y nodejs
          sudo apt-get remove -y npm
      -
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      -
        name: Test Nodejs version
        run: |
          which node
          node --version
          which npm
          npm --version
      -
        name: Build Site
        run: |
          npm install
          npm run build
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
